### ISSUE TITLE
vpd-tool displays incorrect values for keywords with extended characters  

### ISSUE THREAD

**Issue by PriyangaRamasamy** [openbmc/openpower-vpd-parser#11]
vpd-tool truncates n-1 bytes and displays the nth byte of a keyword which has extended characters(or non ascii characters) in it.

**Comment by GiridhariKrishnan** [comment]
Fix is in https://gerrit.openbmc.org/c/openbmc/openpower-vpd-parser/+/62845 for review.

**Comment by GiridhariKrishnan** [comment]
Integrated. 2 weeks ago. can you please close. Thank you.
